config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  scope ":locale", locale:/en|vn/ do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
    resources :users do
      member do
        post :disable_user, :delete_user, :read_notification
      end
      resources :albums do
        # post :like
        member do
          post :like, :follow, :follow_user, :set_private , :disable_user
        end
      end
      resources :pictures do
        member do
          post :like, :follow, :set_private
        end
      end
      resources :notifications
    end
  end
end

app/views/shared/_admin_permission.html.haml
.btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".disable") , disable_user_user_path(user), method: :post
.btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".delete") , delete_user_user_path(user), method: :post,data: { confirm: 'Are you sure?' }

app/views/shared/_album.html.haml
.text-center
  - if user_signed_in?
    - if current_user.is_admin? || current_user.id == params[:user_id].to_i
      %p
        %td= link_to I18n.t(".edit"), edit_user_album_path(album.user,album), {remote:true,class:"btn btn-simple btn-primary btn-lg"}
        %td= link_to I18n.t(".delete") , [album.user,album], method: :delete, class:"btn btn-simple btn-primary btn-lg",data: { confirm: I18n.t(".data_confirm")}
        %td= link_to I18n.t(".private") , set_private_user_album_path(album.user,album), method: :post, class:"btn btn-simple btn-primary btn-lg"
  = link_to user_album_path(album.user,album) do
    = image_tag "album.jpg"
  %p= album.title
  %p= album.description

app/views/shared/_avatar.html.haml
- avatar  = user.avatar.exists? ? image_url(user.avatar.url) : image_path('default-avatar.png')
.avatar
  %img.img-circle.img-responsive.img-raised.image-center{:alt => "Circle Image", :src => "#{avatar}"}/

app/views/shared/_flash.html.haml
.input-group.padding-group.text-center
  %span.input-group-addon
  - flash.each do |key, msg|
    = msg

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-info.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#example-navbar-icons", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Snagi", root_path, class: "navbar-brand"

    #example-navbar-icons.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.material-icons face
              %b.caret
            %ul.dropdown-menu.dropdown-menu-right
              %li.dropdown-header= I18n.t(".authentication")
              %li
                = link_to I18n.t(".log_out"), destroy_user_session_path,:method => :delete
              %li
                = link_to I18n.t(".edit_profile"), edit_user_registration_path
              %li
                = link_to I18n.t(".your_page"), user_albums_path(current_user)
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = "#{@count_un_read_notification} "
              %i.material-icons mail
              %b.caret
            %ul.dropdown-menu.dropdown-menu-right
              - @notifications.each do |notification|
                %li
                  %a{:href => ""}
                  = link_to notification.content, read_notification_user_path(notification),method: :post
        - else
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.material-icons face
              %b.caret
              %ul.dropdown-menu.dropdown-menu-right
                %li
                  = link_to I18n.t(".log_in"), new_user_session_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.material-icons settings
            %b.caret
            %ul.dropdown-menu.dropdown-menu-right
              %li.dropdown-header= I18n.t(".language")
              %li
                = link_to I18n.t(".eng"), locale: "en"
              %li
                = link_to I18n.t(".vn") , locale: "vn"

app/views/shared/_picture.html.haml
.text-center.padding-bot
  - if user_signed_in?
    - if current_user.is_admin? || current_user.id == params[:user_id].to_i
      %p
        %td= link_to I18n.t(".edit") , edit_user_picture_path(picture.album.user,picture), {class:"btn btn-simple btn-primary btn-lg"}
        %td= link_to I18n.t(".delete"), [picture.album.user,picture], method: :delete, class:"btn btn-simple btn-primary btn-lg",data: { confirm: I18n.t(".data_confirm") }
  = link_to user_picture_path(picture.album.user,picture) do
    = image_tag picture.image.url, class: "picture"
  %p= picture.title
  %p= picture.description

app/views/shared/_profile.html.haml
.wrapper
  = render "shared/wallpaper_profile", url: @user
  .main.main-raised
    .container
      .section.text-center
        %h2.title= I18n.t(".list_user")
        .team
          .row
            - @users.each do |user|
              = render "shared/user", user: user

app/views/shared/_user.html.haml
= link_to user_albums_path(user) do
  .col-md-4
    .team-player
      - avatar = user.avatar.exists? ? image_url( user.avatar.url) : image_path("default-avatar.png")
      %img.img-raised.img-circle{:alt => "Thumbnail Image", :src => "#{avatar}"}/
      %h4.title
        = user.name
        %br/
        %small.text-muted
          = user.email
        %br/
        %small.text-muted
        - if user_signed_in?
          - if current_user.is_admin?
            = render "shared/admin_permission", user: user
      %p.description= I18n.t(".lorem")

app/views/shared/_wallpaper.html.haml
.header.header-filter{:style => "background-image: url(#{image_path( url )}"}
  .container
    .row
      .col-md-6
        %h1.title= I18n.t(".title")
        %h4= I18n.t(".lorem")
        %h4= I18n.t(".lorem")

app/views/shared/_wallpaper_profile.html.haml
- wallpaper  = user.wallpaper.exists? ? image_url(user.wallpaper.url) : image_path('wallpaper.jpg')
.header.header-filter{:style => "background-image: url(#{wallpaper}"}

app/views/shared/_wrapper.html.haml
.wrapper
  = render "shared/wallpaper", url: 'wallpaper.jpg'
  .main.main-raised
    .container
      .section.text-center
        %h2.title= I18n.t(".list_user")
        .team
          .row
            - @users.each do |user|
              = render "shared/user", user: user