config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  scope ":locale", locale:/en|vn/ do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
    resources :users do
      member do
        post :disable_user, :delete_user, :read_notification
      end
      resources :albums do
        # post :like
        member do
          post :like, :follow, :follow_user, :set_private , :disable_user
        end
      end
      resources :pictures do
        member do
          post :like, :follow, :set_private
        end
      end
      resources :notifications
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  scope :belongs_to_user, ->(user_id){where('user_id = ?', user_id)}
  scope :not_private, ->{ where(is_private:false) }
  

  after_create :send_notification_user
  after_update :send_notification_album
  belongs_to :user
  has_many :pictures, dependent: :destroy

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :liked_users, through: :likes,source: :user

  has_many :follows, as: :followable ,dependent: :destroy
  has_many :followed_users, through: :follows,source: :user

  validates :title, presence: true
  validates :quality, numericality: { only_integer: true }
  validates :is_private,inclusion: { in: [true, false] }
  private 
  def send_notification_user
    user = self.user
    NotificationService.new({type:"User", id:user.id, album_id:id}).send_notifications 
  end

  def send_notification_album
  	NotificationService.new({type:"Album",id: id}).send_notifications	
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :check_permission , except: :index

  def index
    @albums = AlbumService.new({user_id: params[:user_id].to_i,
                                current_user: current_user,
                                signed_in: user_signed_in?,
                                page: params[:page]}).return_albums
    @user = User.find(params[:user_id])
  end

  def new
    @album = Album.new
    @user = current_user
  end

  def create
    @album = current_user.albums.build(album_params)
    if @album.save
      AlbumService.add_picture(@album,params[:images]) if params[:images]
      redirect_to user_album_path(current_user,@album), notice: I18n.t(".album_create")
    else
      redirect_to new_user_album_path(params[:user_id]), notice: I18n.t(".album_fail")
    end
  end

  def show
    signed_in = user_signed_in? ? true : false

    @pictures = AlbumService.new({user_id: params[:user_id].to_i,
                                  current_user: current_user,
                                  signed_in: signed_in,
                                  page: params[:page],
                                  album: @album}).return_pictures
  end

  def update
    if @album.update(album_params)
      AlbumService.add_picture(@album,params[:images]) if params[:images]
      redirect_to user_album_path(@user,@album), notice: I18n.t(".album_update")
    else
      redirect_to edit_user_album_path(params[:user_id],@album), notice: I18n.t(".album_fail")
    end
  end

  def destroy
    @album.destroy
    redirect_to user_albums_path(@album.user), notice: I18n.t(".album_destroy")
  end

  def like
    LikeService.new({user_id: current_user.id,
                     type: 'Album',id: params[:id]}).like
  end

  def follow
    FollowService.new({user_id: current_user.id,
                       type:' Album',id: params[:id]}).follow
  end

  def follow_user
    FollowService.new({user_id: current_user.id,
                       type: 'User',id: params[:id]}).follow
  end

  def set_private
    SetPrivateService.new({type: 'Album',
                           id: params[:id]}).set_private
  end

  def disable_user
    UserService.new({id: params[:user_id]}).set_active
  end
  private

  def check_permission

    permission = PermissionService.new({current_user: current_user,
                                        owner: params[:user_id],
                                        action: params[:action],
                                        id: params[:id],
                                        type: "Album"}).have_permission?
    redirect_to root_path unless permission
  end

  def set_album
    @album = Album.find(params[:id])
    @pictures = @album.pictures
    @user = User.find(params[:user_id])
    @current_user = current_user
  end

  def album_params
    params.require(:album).permit(:title, :description)
  end
end

app/views/albums/_f.html.haml
.modal-dialog.form-magrin-top
  .modal-content
    = form_for [@user,@album], remote: true, :html => { multipart: true } do |f|
      %h3.text-center= I18n.t(".add_album")
      .input-group.padding-group
        %span.input-group-addon
          %i.material-icons label
        =f.text_field :title, {class:"form-control", placeholder: I18n.t(".form_title") , autofocus: true}
      .input-group.padding-group
        %span.input-group-addon
          %i.material-icons info
        =f.text_field :description, {class:"form-control", placeholder: I18n.t(".form_description") }
      .input-group.padding-group
        %span.input-group-addon
          %i.material-icons attachment
          .controls
            = file_field_tag "images[]",type: :file, multiple: true
      .actions.text-center
        - if params[:action] == "new"
          = f.submit I18n.t(".create") , {class:"btn btn-simple btn-primary btn-lg"}
        - else
          = f.submit I18n.t(".update"), {class:"btn btn-simple btn-primary btn-lg"}
        = link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"}

app/views/albums/_form.html.haml
= render "shared/flash", flash: flash
= form_for [@user,@album], :html => { multipart: true } do |f|
  .input-group.padding-group
    %span.input-group-addon
      %i.material-icons label
    =f.text_field :title, {class:"form-control", placeholder: I18n.t(".form_title") , autofocus: true}
  .input-group.padding-group
    %span.input-group-addon
      %i.material-icons info
    =f.text_field :description, {class:"form-control", placeholder: I18n.t(".form_description") }
  .input-group.padding-group
    %span.input-group-addon
      %i.material-icons attachment
      .controls
        = file_field_tag "images[]",type: :file, multiple: true
  .actions.text-center
    - if params[:action] == "new"
      = f.submit I18n.t(".create") , {class:"btn btn-simple btn-primary btn-lg"}
    - else
      = f.submit I18n.t(".update"), {class:"btn btn-simple btn-primary btn-lg"}

app/views/albums/_form2.html.haml
.modal-dialog.form-magrin-top
  .modal-content
    = form_for [@user,@album], remote: true, :html => { multipart: true } do |f|
      %h3.text-center= I18n.t(".add_album")
      .input-group.padding-group
        %span.input-group-addon
          %i.material-icons label
        =f.text_field :title, {class:"form-control", placeholder: I18n.t(".form_title") , autofocus: true}
      .input-group.padding-group
        %span.input-group-addon
          %i.material-icons info
        =f.text_field :description, {class:"form-control", placeholder: I18n.t(".form_description") }
      .input-group.padding-group
        %span.input-group-addon
          %i.material-icons attachment
          .controls
            = file_field_tag "images[]",type: :file, multiple: true
      .actions.text-center
        - if params[:action] == "new"
          = f.submit I18n.t(".create") , {class:"btn btn-simple btn-primary btn-lg"}
        - else
          = f.submit I18n.t(".update"), {class:"btn btn-simple btn-primary btn-lg"}
        = link_to "Cancel", "#", class: "btn btn-simple btn-primary btn-lg", data: {dismiss: "modal"}

app/views/albums/_new.html.haml
= render "form"

app/views/albums/edit.html.haml
= render "shared/wallpaper_profile", user: @user
.main.main-raised
  .profile-content
    .container
      .row
        .profile
          - p @user
          = render 'shared/avatar' , user: @user
          .name.text-center
            %h3.title= @user.name
            = render 'form', album: @album, user: @user
            = link_to I18n.t(".back") , user_albums_path(@user), {class:"btn btn-simple btn-primary btn-lg"}

app/views/albums/edit.js.erb
$('#modal').html('<%= j render("form2") %>');
$("#modal").modal("show")
$("div.modal-backdrop").hide()

app/views/albums/index.html.haml
= render "shared/wallpaper_profile", user: @user
.main.main-raised
  .profile-content
    .container
      .row
        .profile
          = render 'shared/avatar' , user: @user
          .name.text-center
            %h3.title= @user.name
            - level = @user.is_admin? ? I18n.t(".admin") : I18n.t(".user")
            %h6= level
            %h6= "#{@user.following_users.count} #{I18n.t(".follower") }"
            - if user_signed_in?
              - if current_user.id != params[:user_id].to_i
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".follow") , follow_user_user_album_path(@current_user,@user), method: :post
              - if current_user.id == params[:user_id].to_i
                = link_to I18n.t(".add_album") , new_user_album_path, {class:"btn btn-simple btn-primary btn-lg", remote: true}
              - if current_user.is_admin?
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".disable"), disable_user_user_album_path(@user,@current_user), method: :post
      #modal
      .description.text-center
        %p= I18n.t(".lorem")
      .row
        - @albums.each do |album|
          .col-md-6
            = render 'shared/album', album: album
        .text-center
          = paginate @albums

app/views/albums/new.html.haml
= render "shared/wallpaper_profile", user: @user
.main.main-raised
  .profile-content
    .container
      .row
        .profile
          = render 'shared/avatar' , user: @user
          .name.text-center
            %h3.title= @user.name
            = render 'form', album: @album, user: @user
            = link_to "Back", user_albums_path(@user), {class:"btn btn-simple btn-primary btn-lg"}

app/views/albums/new.js.erb
$('#modal').html('<%= j render("form2") %>');
$("#modal").modal("show")
$("div.modal-backdrop").hide()

app/views/albums/show.html.haml
/- wallpaper = @user.wallpaper == nil ? 'city.jpg' : @user.wallpaper.url

= render "shared/wallpaper_profile", user: @user

.main.main-raised
  .profile-content
    .container
      .row
        .profile
          = render 'shared/avatar' , user: @user
          .name.text-center
            %h3.title= @user.name
            - level = @user.is_admin? ? I18n.t(".admin") : I18n.t(".user")
            %h6= level
            %h6= @album.title
            %h6= "#{@user.following_users.count} #{I18n.t(".follower") }"
            %h6= "#{@album.liked_users.count} #{I18n.t(".likes") }"
            - if user_signed_in?
              .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".follow") , follow_user_album_path(@current_user,@album), method: :post
              .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".like") , like_user_album_path(@current_user,@album), method: :post
              - if current_user.is_admin? || current_user.id == params[:user_id].to_i
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".edit") , edit_user_album_path(@user,@album)
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t ".private" , set_private_user_album_path(@current_user,@album), method: :post
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".delete") , [@user,@album], method: :delete, data: { confirm: I18n.t(".data_confirm") }
      .description.text-center
        %p= @album.description
      .row
        - @pictures.each do |picture|
          .col-md-4
            = render 'shared/picture', picture: picture
        .text-center
          = paginate @pictures