config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  scope ":locale", locale:/en|vn/ do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
    resources :users do
      member do
        post :disable_user, :delete_user, :read_notification
      end
      resources :albums do
        # post :like
        member do
          post :like, :follow, :follow_user, :set_private , :disable_user
        end
      end
      resources :pictures do
        member do
          post :like, :follow, :set_private
        end
      end
      resources :notifications
    end
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  scope :not_private, ->{ where(is_private:false) }
  belongs_to :album

  has_many :likes, as: :likeable
  has_many :liked_users, through: :likes,source: :user

  has_many :follows, as: :followable
  has_many :followed_users, through: :follows,source: :user

  after_create :increase_album_quality
  after_destroy :decrease_ablum_quality

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :image_file_name, presence: true 
  validates :image_content_type, presence: true 
  validates :is_private,inclusion: { in: [true, false] }

  private

  def increase_album_quality
    album.increment!(:quality)
  end

  def decrease_ablum_quality
    album.decrement!(:quality)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :check_permission

  def update
    if @picture.update(picture_params)
      redirect_to [@user, @picture]
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to [@user,@album]
  end

  def like
    LikeService.new({user_id:current_user.id,type:'Picture',id:params[:id]}).like
  end

  def follow
    FollowService.new({user_id:current_user.id,type:'Picture',id:params[:id]}).follow
  end

  def set_private
    SetPrivateService.new({type:'Picture',id:params[:id]}).set_private
  end

  private

  def check_permission
    permission = PermissionService.new({current_user:current_user,
                                        owner:params[:user_id],
                                        action: params[:action],
                                        id:params[:id],
                                        type:"Picture"}).have_permission?
    redirect_to root_path unless permission
  end


  def set_picture
    @picture = Picture.find(params[:id])

    @album = @picture.album
    @user = @album.user
    @current_user = current_user
  end

  def picture_params
    params.require(:picture).permit(:title, :description)
  end
end

app/views/pictures/_form.html.haml
= form_for [@user,@picture] do |f|
  .input-group.padding-group
    %span.input-group-addon
      %i.material-icons label
    =f.text_field :title, {class:"form-control", placeholder: I18n.t(".form_title"), autofocus: true}
  .input-group.padding-group
    %span.input-group-addon
      %i.material-icons info
    =f.text_field :description, {class:"form-control", placeholder: I18n.t(".form_description") }
  .input-group.padding-group
    %span.input-group-addon
      %i.material-icons attachment
    =f.file_field :image, {class:"form-control", placeholder: I18n.t(".image")}
    = image_tag @picture.image.url, class: "image-padding image-padding-max"
  .actions.text-center
    = f.submit I18n.t(".update"), {class:"btn btn-simple btn-primary btn-lg"}

app/views/pictures/edit.html.haml
= link_to "Back", user_picture_path(@user,@picture)

= render "shared/wallpaper_profile",user: @user
.main.main-raised
  .profile-content
    .container
      .row
        .profile
          = render 'shared/avatar' , user: @user
          .name.text-center
            %h3.title= @user.name
            = render 'form', picture: @picture
            = link_to I18n.t(".back") , user_picture_path(@user,@picture), {class:"btn btn-simple btn-primary btn-lg"}

app/views/pictures/show.html.haml
/- wallpaper = @user.wallpaper == nil ? 'city.jpg' : @user.wallpaper.url

= render "shared/wallpaper_profile", user:@user
.main.main-raised
  .profile-content
    .container
      .row
        .profile
          = render 'shared/avatar' , user: @user
          .name.text-center
            %h3.title= @user.name
            - level = @user.is_admin? ? I18n.t(".admin") : I18n.t(".user")
            %h6= level
            %h6= @picture.title
            %h6= @picture.description
            %h6= "#{@picture.followed_users.count} #{I18n.t(".follower") }"
            %h6= "#{@picture.liked_users.count} #{I18n.t(".likes") }"
            - if user_signed_in?
              .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".update"), follow_user_picture_path(@current_user,@picture), method: :post
              .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".like"), like_user_picture_path(@current_user,@picture), method: :post
              - if current_user.is_admin? || current_user.id == params[:user_id].to_i
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".edit"), edit_user_picture_path(@user,@picture)
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".private"), set_private_user_picture_path(@current_user,@picture), method: :post
                .btn.btn-simple.btn-primary.btn-lg= link_to I18n.t(".delete"), [@user,@picture], method: :delete, data: { confirm: I18n.t(".data_confirm") }
      .row.text-center
        %p= image_tag @picture.image.url, class:"image-padding"